//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bustransfer
    {
        public int bustransferid { get; set; }
        public int busid { get; set; }
        public int depoid { get; set; }
        public System.DateTime updateddate { get; set; }
        public int updatedby { get; set; }
        public bool buscurenntdepo { get; set; }
    }
}
