//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChitFuel
    {
        public int chitfuelid { get; set; }
        public int vechilenumber { get; set; }
        public int fueltype { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public string otherfule { get; set; }
        public string otherprice { get; set; }
        public int dieselbookno { get; set; }
        public int dieselchitno { get; set; }
        public int stationid { get; set; }
        public int insertedby { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> inserteddate { get; set; }
    }
}
