//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_finalStock
    {
        public int dailyid { get; set; }
        public int pumpid { get; set; }
        public Nullable<long> smeter_petrol { get; set; }
        public Nullable<long> emeter_petrol { get; set; }
        public Nullable<decimal> ownersale_petrol { get; set; }
        public Nullable<decimal> cashsale_petrol { get; set; }
        public Nullable<decimal> staffsale_petrol { get; set; }
        public Nullable<decimal> othersale_petrol { get; set; }
        public Nullable<decimal> ownerquanity_petrol { get; set; }
        public Nullable<decimal> cashquanity_petrol { get; set; }
        public Nullable<decimal> staffquanity_petrol { get; set; }
        public Nullable<decimal> otherquanity_petrol { get; set; }
        public Nullable<long> smeter_diesel { get; set; }
        public Nullable<long> emeter_diesel { get; set; }
        public Nullable<decimal> ownersale_diesel { get; set; }
        public Nullable<decimal> cashsale_diesel { get; set; }
        public Nullable<decimal> staffsale_diesel { get; set; }
        public Nullable<decimal> othersale_diesel { get; set; }
        public Nullable<decimal> ownerquanity_diesel { get; set; }
        public Nullable<decimal> cashquanity_diesel { get; set; }
        public Nullable<decimal> staffquanity_diesel { get; set; }
        public Nullable<decimal> otherquanity_diesel { get; set; }
        public Nullable<decimal> ownersale_lub { get; set; }
        public Nullable<decimal> cashsale_lub { get; set; }
        public Nullable<decimal> staffsale_lub { get; set; }
        public Nullable<decimal> othersale_lub { get; set; }
        public Nullable<decimal> ownerquanity_lub { get; set; }
        public Nullable<decimal> cashquanity_lub { get; set; }
        public Nullable<decimal> staffquanity_lub { get; set; }
        public Nullable<decimal> otherquanity_lub { get; set; }
        public Nullable<System.DateTime> summary_date { get; set; }
        public Nullable<int> inserted_by { get; set; }
    }
}
