//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_backDepo
    {
        public int serialid { get; set; }
        public Nullable<int> busid { get; set; }
        public string bus_numer { get; set; }
        public string ownername { get; set; }
        public string dipo { get; set; }
        public string bankaccount { get; set; }
        public string bankname { get; set; }
    }
}
