//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashVivrani
    {
        public int vivrani_serial_id { get; set; }
        public int emp_id { get; set; }
        public int emp_department { get; set; }
        public System.DateTime date { get; set; }
        public bool Issubmited { get; set; }
        public int vivrani_serial_number { get; set; }
    
        public virtual tblEmployeeQuick tblEmployeeQuick { get; set; }
        public virtual tblMasterDepartment tblMasterDepartment { get; set; }
    }
}
