//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeQuick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployeeQuick()
        {
            this.tbl_CashVivrani = new HashSet<tbl_CashVivrani>();
        }
    
        public int serial_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public int department_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public string confirm_password { get; set; }
    
        public virtual tblMasterDepartment tblMasterDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CashVivrani> tbl_CashVivrani { get; set; }
    }
}
