//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasterDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMasterDepartment()
        {
            this.tblEmployeeQuicks = new HashSet<tblEmployeeQuick>();
            this.tbl_CashVivrani = new HashSet<tbl_CashVivrani>();
        }
    
        public int id { get; set; }
        public string department_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeQuick> tblEmployeeQuicks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CashVivrani> tbl_CashVivrani { get; set; }
    }
}
