//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmou.DataRepository.EntityRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_cashvivrani
    {
        public int vivrani_id { get; set; }
        public decimal amount { get; set; }
        public string cash_vivrani_id { get; set; }
        public int bus_number { get; set; }
        public System.DateTime waybill_insertdate { get; set; }
        public int waybillno { get; set; }
        public int waybillserialno { get; set; }
        public int ticket_from { get; set; }
        public int ticket_to { get; set; }
        public string station_from { get; set; }
        public string station_to { get; set; }
        public System.DateTime vivrani_inserted_date { get; set; }
        public int emp_id { get; set; }
        public Nullable<decimal> roundOffAmount { get; set; }
    }
}
